;FILENAME: EXA132.ASM
;统计字符串中B到E的个数，并二进制显示在屏幕
.586
DATAS SEGMENT USE16
BUF DB 'IBCD' ;自定义字符串
LEN EQU $-BUF;字符串长度
DATAS ENDS
CODES SEGMENT USE16
    ASSUME CS:CODES,DS:DATAS
START:  MOV AX,DATAS
	    MOV DS,AX
	    MOV BX,OFFSET BUF
 	    MOV CX,LEN
	    MOV DL,0;符合条件的字符个数
LAST:   CMP BYTE PTR[BX],42H
	    JC  NO
	    CMP BYTE PTR[BX],45H
	    JA  NO
	    INC DX
NO:     INC BX
		LOOP LAST	    
        CALL DISP
        MOV DL,42H
        MOV AH,2
	    INT 21H	
	    MOV AH,4CH
	    INT 21H	
DISP PROC
	    MOV CX,8
SHOW:	MOV AL,'0'
		SAL DL,1
		JC ONEDIS
		SUB AL,1
ONEDIS: ADD AL,1
		MOV AH,0EH
	    INT 10H	
	    LOOP SHOW
		RET
DISP ENDP
CODES ENDS
    END START

